inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

# This app has custom find_by methods
Rails/DynamicFindBy:
  Whitelist:
    - find_by_param
    - find_by_document
