require: rubocop-rspec

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config.ru
    - db/schema.rb
    - tmp/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
    - 'db/migrate/*.rb'

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_param
    - find_by_document

Rails/SaveBang:
  Enabled: true

Style/DateTime:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/features/**/*.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
