require: rubocop-rspec

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config.ru
    - db/schema.rb
    - tmp/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
    - 'db/migrate/*.rb'

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

# While using has_many/through does have some advantages,
# it also requires a significant amount of boilerplate code:
#
# - An additional 'has_many :join_table' statement
# - An additional class for the join table (model)
#
# This Cop/rule appears to have been written with the
# assumption that all join tables have inherent meaning,
# we want to represent, which is not the case; sometimes
# relationships are just # many-to-many, and that's it.
#
# This should be disabled in a new release of rubocop-govuk
Rails/HasAndBelongsToMany:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_param
    - find_by_document

Rails/SaveBang:
  Enabled: true

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: "strict"

Style/DateTime:
  Enabled: true

# Rubocop RSpec rules
# We are trialling these set in app before intending to push the config to
# rubocop-govuk

# Don't require examples to be below a particular number of lines
RSpec/ExampleLength:
  Enabled: false

# Don't force the top level describe to be a class, we tend to be good at
# sticking to the class convention and only deviate for valid cases like rake
# tasks
RSpec/DescribeClass:
  Enabled: false

# We accept multiple expectations (within reason), preferring them to running
# mulitple similar tests
RSpec/MultipleExpectations:
  Enabled: false

# Within GOV.UK we use Capybara test method syntax of feature, scenario. We
# don't want this outside of feature specs though
Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/**/*.rb'

# Part of the GOV.UK feature spec style involves instance variables
RSpec/InstanceVariable:
  Exclude:
    - 'spec/features/**/*.rb'

# In GOV.UK we quite often test that a class received a particular method
RSpec/MessageSpies:
  Enabled: false

# This prevents nesting context blocks. This practice is hard to understand
# but unfortunately is in some GOV.UK apps.
# TODO: Investigate if we can embrace this rule and remove our nesting
RSpec/NestedGroups:
  Enabled: false
