---
- id: news_story
  label: News story
  path_prefix: /government/news
  images: true
  check_path_conflict: true
  publishing_metadata:
    schema_name: news_article
    rendering_app: government-frontend
  contents:
    - title_and_base_path
    - summary
    - body
  tags:
    - id: primary_publishing_organisation
      type: single_tag
      document_type: organisation
    - id: organisations
      type: multi_tag
      document_type: organisation
    - id: role_appointments
      type: multi_tag
      document_type: role_appointment
    - id: topical_events
      type: multi_tag
      document_type: topical_event
    - id: world_locations
      type: multi_tag
      document_type: world_location

- id: press_release
  label: Press release
  path_prefix: /government/news
  images: true
  check_path_conflict: true
  publishing_metadata:
    schema_name: news_article
    rendering_app: government-frontend
  contents:
    - title_and_base_path
    - summary
    - body
  tags:
    - id: primary_publishing_organisation
      type: single_tag
      document_type: organisation
    - id: organisations
      type: multi_tag
      document_type: organisation
    - id: role_appointments
      type: multi_tag
      document_type: role_appointment
    - id: topical_events
      type: multi_tag
      document_type: topical_event
    - id: world_locations
      type: multi_tag
      document_type: world_location
