---
- id: news_story
  label: News story
  path_prefix: /government/news
  images: true
  check_path_conflict: true
  publishing_metadata:
    schema_name: news_article
    rendering_app: government-frontend
  contents:
    - title_and_base_path
    - summary
    - body
  tags:
    - id: primary_publishing_organisation
      type: single_tag
      document_type: organisation
    - id: organisations
      type: multi_tag
      document_type: organisation
    - id: role_appointments
      type: multi_tag
      document_type: role_appointment
    - id: topical_events
      type: multi_tag
      document_type: topical_event
    - id: world_locations
      type: multi_tag
      document_type: world_location

- id: press_release
  label: Press release
  path_prefix: /government/news
  images: true
  check_path_conflict: true
  publishing_metadata:
    schema_name: news_article
    rendering_app: government-frontend
  contents:
    - title_and_base_path
    - summary
    - body
  tags:
    - id: primary_publishing_organisation
      type: single_tag
      document_type: organisation
    - id: organisations
      type: multi_tag
      document_type: organisation
    - id: role_appointments
      type: multi_tag
      document_type: role_appointment
    - id: topical_events
      type: multi_tag
      document_type: topical_event
    - id: world_locations
      type: multi_tag
      document_type: world_location

- id: fatality_notice
  label: Fatality notice
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/fatalities/new

- id: speech
  label: Speech
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/speeches/new

- id: world_news_story
  label: World news story
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/news/new

- id: detailed_guide
  label: Detailed guide
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/detailed-guides/new

- id: any-whitehall-publication
  label: Publication
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/publications/new

- id: manual
  label: Manual
  managed_elsewhere:
    hostname: manuals-publisher
    path: /

- id: any-mainstream-publication
  label: Mainstream guide
  managed_elsewhere:
    hostname: support
    path: /content_change_request/new

- id: travel_advice
  label: Travel advice
  managed_elsewhere:
    hostname: travel-advice-publisher
    path: /admin

- id: statistical-data-set
  label: Statistical data set
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/statistical-data-sets/new

- id: case_study
  label: Case study
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/case-studies/new

- id: consultation
  label: Consultation
  managed_elsewhere:
    hostname: whitehall-admin
    path: /government/admin/consultations/new
