---
:verbose: false
:concurrency: 10
:max_retries: 0
:logfile: ./log/sidekiq.json.log
development:
  :logfile: null
:queues:
  - default
  - mailers
:schedule:
  update_contacts:
    interval: ['15m', first_in: '0s']
    class: UpdateContactsJob

